name: scc_web
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  intl: ^0.18.0
  flutter_portal: ^1.1.3
  gap: ^3.0.1
  heroicons: ^0.8.0
  auto_route: ^5.0.4
  flutter_svg: ^2.0.6
  get_it: ^7.3.0
  dotted_border: ^2.0.0+1
  shimmer: ^2.0.0
  flutter_dropzone: ^3.0.0
  file_picker: ^4.1.2
  styled_text: ^4.0.0+1
  simple_gesture_detector: ^0.2.0
  universal_html: ^2.2.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  flutter_html: ^3.0.0-alpha.6
  intl_phone_field: ^3.1.0
  super_tooltip: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.0
  flutter_typeahead: ^4.3.8
  intl_phone_number_input: ^0.7.3+1
  flutter_iconly: ^1.0.2
  toggle_switch: ^2.1.0
  timelines: ^0.1.0
  clippy_flutter: ^2.0.0-nullsafety.1
  percent_indicator: ^4.2.3
  pointer_interceptor: ^0.9.3+7
  material_design_icons_flutter: ^7.0.7296
  syncfusion_flutter_maps: ^21.2.10
  syncfusion_flutter_charts: ^21.2.10
  dio: ^5.3.3
  http_mock_adapter: ^0.4.2
  dropdown_button2: ^2.3.9
  syncfusion_flutter_core: ^21.2.10
  enhance_stepper: ^0.1.1
  tuple: ^2.0.0
  im_stepper: ^1.0.1+1
  flutter_osm_plugin: ^0.70.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.3
  build_runner: ^2.1.2
  build_web_compilers: ^3.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/web.env

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    # - family: Open Sans
    #   fonts:
    #     - asset: assets/fonts/OpenSans-Regular.ttf
    #       # weight: 400
    #     - asset: assets/fonts/OpenSans-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/OpenSans-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/OpenSans-Light.ttf
    #       weight: 300
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto-Regular.ttf
    #       # weight: 400
    #     - asset: assets/fonts/Roboto-Bold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Roboto-Light.ttf
    #       weight: 300
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 600
          # style: bold
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
    - family: toyota
      fonts:
        - asset: assets/fonts/Toyota-Type-Book-1.otf
          weight: 100
        - asset: assets/fonts/Toyota-Type-Light-1.otf
          weight: 200
        - asset: assets/fonts/Toyota-Type-Regular.otf
        - asset: assets/fonts/Toyota-Type-Semibold-1.ttf
          weight: 400
        - asset: assets/fonts/Toyota-Type-Bold-1.otf
          weight: 600
        - asset: assets/fonts/Toyota-Type-Black.ttf
          weight: 800
    - family: VccIcon
      fonts:
        - asset: assets/fonts/VccIcon.ttf
